### ISSUE TITLE
Reading Page is not opening

### ISSUE THREAD

**Issue by EnternalDemon** [nanihadesuka/NovelDokusha#121]
Whenever I try to open a chapter it restart app, I can't get access to reading Page.

Device: Oppo A16
Android Version: 11

It's happening in new version.

**Comment by nanihadesuka** [comment]
Need info:
- What source
- What novel
- Chapter

**Comment by EnternalDemon** [comment]
> Need info:
> 
> * What source
> * What novel
> * Chapter

No it's happening in every source and novel I even tried on local but it's still not worked, as I clicked on chapter it restart app.

**Comment by EnternalDemon** [comment]
No it's happening in every source and novel I even tried on local but it's still not worked, as I clicked on chapter it restart app.

**Comment by egerardoqd** [comment]
Same here. A11.
When I try to open any novel from any source the reader crash and it back to the catalog. I don't know if this can help but this is the logcat in my device

```
FATAL EXCEPTION: main
Process: my.noveldokusha, PID: 13856
java.lang.IncompatibleClassChangeError: Class 'android.content.res.TypedArray' does not implement interface 'java.lang.AutoCloseable' in call to 'void java.lang.AutoCloseable.close()' (declaration of 'androidx.work.Operation$1' appears in base.apk)
	at androidx.work.Operation$1.colorAttrRes(Unknown Source:28)
	at my.noveldokusha.features.reader.ReaderActivity.onCreate(Unknown Source:696)
	at android.app.Activity.performCreate(Activity.java:8000)
	at android.app.Activity.performCreate(Activity.java:7984)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7661)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by nanihadesuka** [comment]
03ec9af with the fix

**Comment by egerardoqd** [comment]
Is fixed in latest version. Thank you.
