### ISSUE TITLE
Indo Source: Sakura Novel crash

### ISSUE THREAD

**Issue by OshekharO** [nanihadesuka/NovelDokusha#123]
Unknown error.

Info:
No Info

Message:
java.lang.NullPointerException: getCookie(...) must not be null

Stacktrace:
java.io.IOException: java.lang.NullPointerException: getCookie(...) must not be null
	at my.noveldokusha.network.interceptors.CloudFareVerificationInterceptor.intercept(Unknown Source:134)
	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:127)
	at my.noveldokusha.network.interceptors.DecodeResponseInterceptor.intercept(Unknown Source:2)
	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:127)
	at my.noveldokusha.network.interceptors.UserAgentInterceptor.intercept(Unknown Source:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:127)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(Unknown Source:95)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(Unknown Source:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: getCookie(...) must not be null
	at my.noveldokusha.network.interceptors.CloudFareVerificationInterceptor.intercept(Unknown Source:61)
	... 10 more

**Comment by nanihadesuka** [comment]
2be7a17845ad20694b95a38fe617ee32ced5df3d Added message for real cause and steps to try solve it. (Take into account that cloudfare must have changed done some changes as the bypass doesn't seem to work anymore)
