### ISSUE TITLE
Portuguese Source: Saikai crash 

### ISSUE THREAD

**Issue by OshekharO** [nanihadesuka/NovelDokusha#126]
Unknown error.

Info:
No Info

Message:
Unable to resolve host "api.saikai.com.br": No address associated with hostname

Stacktrace:
java.net.UnknownHostException: Unable to resolve host "api.saikai.com.br": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at okhttp3.Dns$Companion$DnsSystem.lookup(Unknown Source:5)
	at okhttp3.internal.connection.RealRoutePlanner.plan(Unknown Source:436)
	at okhttp3.internal.connection.FastFallbackExchangeFinder.launchTcpConnect(Unknown Source:9)
	at okhttp3.internal.connection.FastFallbackExchangeFinder.find(Unknown Source:68)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(Unknown Source:27)
	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:127)
	at okhttp3.internal.cache.CacheInterceptor.intercept(Unknown Source:923)
	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:127)
	at okhttp3.internal.http.BridgeInterceptor.intercept(Unknown Source:219)
	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:127)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(Unknown Source:165)
	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:127)
	at my.noveldokusha.network.interceptors.CloudFareVerificationInterceptor.intercept(Unknown Source:4)
	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:127)
	at my.noveldokusha.network.interceptors.DecodeResponseInterceptor.intercept(Unknown Source:2)
	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:127)
	at my.noveldokusha.network.interceptors.UserAgentInterceptor.intercept(Unknown Source:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:127)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(Unknown Source:95)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(Unknown Source:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:222)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
	... 25 more

**Comment by nanihadesuka** [comment]
2be7a17845ad20694b95a38fe617ee32ced5df3d Added message for real cause and steps to try solve it. (Take into account that cloudfare must have changed done some changes as the bypass doesn't seem to work anymore)
