### ISSUE TITLE
crashing app when selecting ebook from library

### ISSUE THREAD

**Issue by SHAMSRIZWAN** [nanihadesuka/NovelDokusha#84]
FATAL EXCEPTION: main
                 Process: my.noveldokusha, PID: 3061
                 java.lang.NullPointerException
                 	at my.noveldokusha.ui.screens.chaptersList.ChaptersViewModel.<init>(ChaptersViewModel.kt:78)
                 	at my.noveldokusha.DaggerApp_HiltComponents_SingletonC$ViewModelCImpl$SwitchingProvider.get(DaggerApp_HiltComponents_SingletonC.java:675)
                 	at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory$1.create(HiltViewModelFactory.java:102)
                 	at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.kt:90)
                 	at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory.create(HiltViewModelFactory.java:114)
                 	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
                 	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
                 	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:53)
                 	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:35)
                 	at my.noveldokusha.ui.screens.chaptersList.ChaptersActivity.getViewModel(ChaptersActivity.kt:40)
                 	at my.noveldokusha.ui.screens.chaptersList.ChaptersActivity$onCreate$1$1.invoke(ChaptersActivity.kt:56)
                 	at my.noveldokusha.ui.screens.chaptersList.ChaptersActivity$onCreate$1$1.invoke(ChaptersActivity.kt:46)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                 	at androidx.compose.material3.TextKt.ProvideTextStyle(Text.kt:360)
                 	at androidx.compose.material3.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:81)
                 	at androidx.compose.material3.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:80)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                 	at androidx.compose.material3.MaterialThemeKt.MaterialTheme(MaterialTheme.kt:73)
                 	at my.noveldokusha.ui.theme.ThemeKt$InternalTheme$1.invoke(Theme.kt:96)
                 	at my.noveldokusha.ui.theme.ThemeKt$InternalTheme$1.invoke(Theme.kt:95)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                 	at my.noveldokusha.ui.theme.ThemeKt.InternalTheme(Theme.kt:92)
                 	at my.noveldokusha.ui.theme.ThemeKt.Theme(Theme.kt:63)
                 	at my.noveldokusha.ui.screens.chaptersList.ChaptersActivity$onCreate$1.invoke(ChaptersActivity.kt:46)
                 	at my.noveldokusha.ui.screens.chaptersList.ChaptersActivity$onCreate$1.invoke(ChaptersActivity.kt:45)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                 	at androidx.compose.ui.platform.ComposeView.Content(ComposeView.android.kt:428)
                 	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:252)
                 	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:251)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                 	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:194)
                 	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:123)
05:46:49.041  E  	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:122)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                 	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:114)
                 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Wrapper.android.kt:156)
                 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$2.invoke(Wrapper.android.kt:155)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                 	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:155)
                 	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:140)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                 	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:78)
                 	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3373)
                 	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3363)
                 	at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
                 	at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
                 	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3363)
                 	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3298)
                 	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:587)
                 	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:966)
                 	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:519)
                 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:140)
                 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
                 	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:1099)
                 	at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:131)
                 	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:181)
                 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)
                 	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.kt:192)
                 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:138)
                 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
                 	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1174)
                 	at android.view.View.dispatchAttachedToWindow(View.java:20479)
                 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3489)
                 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
                 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
                 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
                 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
                 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
                 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
                 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2417)
                 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1952)
05:46:49.043  E  	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8171)
                 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
                 	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
                 	at android.view.Choreographer.doFrame(Choreographer.java:731)
                 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
                 	at android.os.Handler.handleCallback(Handler.java:938)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loop(Looper.java:223)
                 	at android.app.ActivityThread.main(ActivityThread.java:7656)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by nanihadesuka** [comment]
Fixed in #b24a52deb76b08360eeebc96ad005231fd9f82fe
A release will probably be made next week.

**Comment by SHAMSRIZWAN** [comment]
thank you so much
